return {
  -- Normal = {  bg = "#000000" },
  CursorLine = { ctermbg = 236, bg = "#303030" },
  NotifyBackground = { link = "Normal" },
  Comment = { fg = "Grey" },
  GitSignsAdd = { ctermfg = 2, fg = "Green" },
  GitSignsChange = { ctermfg = 172, fg = "Orange" },
  GitSignsDelete = { ctermfg = 1, fg = "Red" },
  SignColumn = {},
  FoldColumn = {},
  Pmenu = { ctermfg = 235, bg = "#262626" },
  WinSeparator = { ctermfg = 236, fg = "Grey" },
  MatchParen = { bg = "DarkCyan" },
  Delimiter = { link = "Special" },
}
