return { -- this table overrides highlights in all themes
  -- Normal = {  bg = "#000000" },
  -- CursorLine = { ctermbg = 236, bg = "#303030" },
  NotifyBackground = { link = "Normal" },
  -- Comment = { fg = "Grey" },
  GitSignsAdd = { ctermfg = 2, fg = "Green" },
  GitSignsChange = { ctermfg = 172, fg = "Orange" },
  GitSignsDelete = { ctermfg = 1, fg = "Red" },
  SignColumn = {},
  FoldColumn = {},
  Pmenu = { link = "Normal" },
  WinSeparator = { ctermfg = 243, fg = "#767676" },
  StatusLine = { ctermfg = 234, ctermbg = 247, fg = "#1c1c1c", bg = "#9e9e9e" },
  -- MatchParen = { bg = "DarkCyan" },
  -- Delimiter = { link = "Special" },
}
